### PR TITLE
TuanHT3-Verify click on highlight Zip Code link located under Car Name on Review Page and Input Zip Code To Change Vehicle Zip Code and displayed location

### PR DESCRIPTION
**Pull request by tuankyle2408**

### CODE REVIEW

**Comment by namnguyen-itvn** [comment]
@lanhvokhuyet please review this Pull Request

**Review by nguyenhoaiai — COMMENTED** [review]
- Coding convention: fine
- Source run : not run source (o is not a function error)
- Have not used Data Driven

**Comment by tuankyle2408** [comment]
> * Coding convention: fine
> * Source run : not run source (o is not a function error)
> * Have not used Data Driven

Plesea enable "TestNG" extensions on VS Code, I have taken the source code back and run test case is still normal

**Review by namnguyen-itvn — COMMENTED** [review]
1. cai gi do
2. cai gi the
3. cai gi day

**Pull request closed without merging**
